import type { InventoryItem } from "./types";

export const locations = [
  { name: "Garage", path: "Home / Garage", count: 3, color: "sage" },
  { name: "Office", path: "Home / Office", count: 2, color: "blue" },
  { name: "Gear closet", path: "Home / Hall / Gear closet", count: 2, color: "sand" },
  { name: "Kitchen", path: "Home / Kitchen", count: 1, color: "coral" },
];

export const collections = [
  { name: "Photography", count: 2, icon: "◎", color: "#dbe8e2" },
  { name: "Camping", count: 2, icon: "△", color: "#e9e0cd" },
  { name: "Electronics", count: 2, icon: "⌁", color: "#dce5ef" },
  { name: "Workshop", count: 2, icon: "◇", color: "#ecdcd3" },
];

export const seedItems: InventoryItem[] = [
  {
    id: "camera-x100v",
    name: "Fujifilm X100V",
    category: "Cameras",
    location: "Home / Office / Camera cabinet",
    collections: ["Photography"],
    tags: ["travel", "everyday carry"],
    notes: "Everyday camera. Keep the spare battery in the small canvas pouch.",
    purchaseDate: "2022-04-18",
    purchasePrice: 1399,
    estimatedValue: 1240,
    manufacturer: "Fujifilm",
    model: "X100V",
    serialNumber: "13A02741",
    condition: "Excellent",
    photo: null,
    visual: "camera",
    createdAt: "2026-07-24T10:30:00.000Z",
    updatedAt: "2026-07-24T10:30:00.000Z",
  },
  {
    id: "camp-stove",
    name: "PocketRocket stove",
    category: "Outdoor",
    location: "Home / Hall / Gear closet / Green tote",
    collections: ["Camping"],
    tags: ["cooking", "backpacking"],
    notes: "Fuel canister stored separately on the upper shelf.",
    purchaseDate: "2023-06-02",
    purchasePrice: 84.95,
    estimatedValue: 65,
    manufacturer: "MSR",
    model: "PocketRocket Deluxe",
    serialNumber: "",
    condition: "Good",
    photo: null,
    visual: "stove",
    createdAt: "2026-07-22T16:15:00.000Z",
    updatedAt: "2026-07-22T16:15:00.000Z",
  },
  {
    id: "headphones",
    name: "Studio headphones",
    category: "Electronics",
    location: "Home / Office / Desk / Left drawer",
    collections: ["Electronics"],
    tags: ["audio", "work"],
    notes: "Coiled cable and adapter are in the same drawer.",
    purchaseDate: "2021-11-26",
    purchasePrice: 149,
    estimatedValue: 95,
    manufacturer: "Beyerdynamic",
    model: "DT 770 Pro",
    serialNumber: "",
    condition: "Good",
    photo: null,
    visual: "headphones",
    createdAt: "2026-07-19T08:45:00.000Z",
    updatedAt: "2026-07-19T08:45:00.000Z",
  },
  {
    id: "toolbox",
    name: "Precision tool set",
    category: "Tools",
    location: "Home / Garage / Workbench / Drawer 1",
    collections: ["Workshop"],
    tags: ["repair", "small parts"],
    notes: "Complete 64-piece set.",
    purchaseDate: "2024-02-12",
    purchasePrice: 72,
    estimatedValue: 60,
    manufacturer: "iFixit",
    model: "Mako",
    serialNumber: "",
    condition: "Excellent",
    photo: null,
    visual: "tools",
    createdAt: "2026-07-15T13:20:00.000Z",
    updatedAt: "2026-07-15T13:20:00.000Z",
  },
  {
    id: "binoculars",
    name: "Trail binoculars",
    category: "Outdoor",
    location: "Home / Hall / Gear closet / Top shelf",
    collections: ["Camping", "Photography"],
    tags: ["birding", "travel"],
    notes: "Lens cloth is inside the case.",
    purchaseDate: "",
    purchasePrice: null,
    estimatedValue: 180,
    manufacturer: "Nikon",
    model: "Monarch M5 8x42",
    serialNumber: "BA41920",
    condition: "Excellent",
    photo: null,
    visual: "binoculars",
    createdAt: "2026-07-11T11:10:00.000Z",
    updatedAt: "2026-07-11T11:10:00.000Z",
  },
  {
    id: "drill",
    name: "Cordless drill",
    category: "Tools",
    location: "Home / Garage / Shelf A / Black case",
    collections: ["Workshop"],
    tags: ["power tool"],
    notes: "Two batteries. Charger lives on the workbench.",
    purchaseDate: "2020-09-14",
    purchasePrice: 189,
    estimatedValue: 110,
    manufacturer: "Makita",
    model: "XFD13",
    serialNumber: "1184037",
    condition: "Good",
    photo: null,
    visual: "drill",
    createdAt: "2026-07-05T09:30:00.000Z",
    updatedAt: "2026-07-05T09:30:00.000Z",
  },
  {
    id: "moka-pot",
    name: "Moka Express",
    category: "Kitchen",
    location: "Home / Kitchen / Upper cabinet",
    collections: [],
    tags: ["coffee"],
    notes: "Six-cup size.",
    purchaseDate: "",
    purchasePrice: null,
    estimatedValue: 38,
    manufacturer: "Bialetti",
    model: "Moka Express 6-cup",
    serialNumber: "",
    condition: "Good",
    photo: null,
    visual: "moka",
    createdAt: "2026-06-28T07:50:00.000Z",
    updatedAt: "2026-06-28T07:50:00.000Z",
  },
  {
    id: "ssd",
    name: "Portable SSD",
    category: "Electronics",
    location: "Home / Office / File cabinet / Tech pouch",
    collections: ["Electronics"],
    tags: ["backup", "travel"],
    notes: "",
    purchaseDate: "2024-11-21",
    purchasePrice: 119,
    estimatedValue: null,
    manufacturer: "Samsung",
    model: "T7 Shield 2TB",
    serialNumber: "S6Y4NJ0R9201",
    condition: "Excellent",
    photo: null,
    visual: "ssd",
    createdAt: "2026-06-20T15:00:00.000Z",
    updatedAt: "2026-06-20T15:00:00.000Z",
  },
];
